[build]
publish = "bin/Release/net8.0/publish/wwwroot"
command = "dotnet publish -c Release"

[[redirects]]
from = "/booth/*"
to = "https://xframe.netlify.app/booth/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
